import Head from 'next/head';

const metadata = {
  title: '_Portfolio/contact',
  description: 'Generated by Next.js',
};


const Contact = () => {
  return (
  <div>
    <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
    Contact
    </div>
    )
};

export default Contact;
