import Head from 'next/head';


const metadata = {
  title: '_Portfolio/services',
  description: 'Generated by Next.js',
};


const Services = () => {
  return (
  <div>
    <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
    Services
    </div>
    )
};

export default Services;
