import {Sora} from '@next/font/google';
import Navbar from '../components/Nav'
import Header from '../components/Header';
import TopLeftImg from '../components/TopLeftImg'
import Head from 'next/head';

const sora = Sora({
  subsets: ['latin'],
  variable: '--font-sora',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800']
});

const metadata = {
  title: '_Portfolio_',
  description: 'Generated by Next.js',
};


const Layout = ({children}) => {
  return (
    <div className={`page bg-site text-white bg-cover bg-no-repeat ${sora.variable} font-sora relative`}>
       <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
  {/* <TopLeftImg/> */}
  <Navbar/>
  <Header/>
  {children}
  </div>
  );
 
};

export default Layout;
