import Head from 'next/head';

const metadata = {
  title: '_Portfolio/testimonials',
  description: 'Generated by Next.js',
};



const Testimonials = () => {
  return (
  <div>
    <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
    Testimonials
    </div>
    )
};

export default Testimonials;
