import Head from 'next/head';


const metadata = {
  title: '_Portfolio/work',
  description: 'Generated by Next.js',
};


const Work = () => {
  return (
  <div>
    <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
    Work
    </div>
  )
};

export default Work;
